spring.application.name=lolapi
spring.datasource.url= postgresql://neondb_owner:npg_EqFe8jIiahV3@ep-bold-sunset-ad31uybp-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=Yoruke200!
spring.jpa.hibernate.ddl-auto=update



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE